fix: detects payload signature prefix
monkeydioude/josuke pull request #10
Opened 2022-04-28 16:01 UTC by pyxide

2022-05-04 08:26 UTC, monkeydioude requested changes

2022-05-04 08:26 UTC, monkeydioude commented on hooks.go
> +			digestName = requestSignature[0: equalIndex]
Je crois que tu peux juste faire `requestSignature[: equalIndex]`

2022-05-04 08:26 UTC, monkeydioude commented on hooks.go
> +			requestSignature = requestSignature[equalIndex + 1: len(requestSignature)]
Ici tu dois pouvoir faire `requestSignature[equalIndex + 1:]`

2022-05-04 08:26 UTC, monkeydioude commented on hooks.go
> +			requestSignature = requestSignature[equalIndex + 1: len(requestSignature)]
Petit exemple: https://go.dev/play/p/dlQJb1lw83d

2022-05-04 08:26 UTC, monkeydioude commented on hooks.go
> +			digestName = requestSignature[0: equalIndex]
Petit exemple:  https://go.dev/play/p/dlQJb1lw83d

2022-05-10 09:11 UTC, oparent-sharecare commented on hooks.go
> +			digestName = requestSignature[0: equalIndex]
c’est fait.

2022-05-10 09:11 UTC, oparent-sharecare commented on hooks.go
> +			requestSignature = requestSignature[equalIndex + 1: len(requestSignature)]
c’est tellement bourré de sucre syntactique que j’ai attrapé une carie.

2022-05-14 17:12 UTC, monkeydioude approved these changes

2022-05-14 17:13 UTC, merged