Hook definition and handler, check HMAC signature, write payload
monkeydioude/josuke pull request #3
Opened 2021-10-11 00:47 UTC by pyxide

Refactoring, based on tag `v1.1.0`, __Breaking changes__.
- removed `github_hook` and `bitbucket_hook` properties, added full fledged `hook` definitions. New optional command at hook level that takes precedence over deployment commands.
  ```json
  "hook": [
  	{
  		"name": "gogs",
  		"type": "gogs",
  		"path": "/josuke/gogs",
  		"secret": "GogoGadgetoGogs",
  		"command": [ "/home/me/josuke-hook", "%payload_path%"]
  	}
  ]
  ```
  Uses a new structure `HookHandler`, that has a Josuke and a Hook reference.
- Gogs hook implementation. « C’est une honte, c’est un scandale ! », the Go Git Service was not implemented!
- HMAC 256 payload signature checks for Gogs and GitHub.
- new placeholder `%payload_path%`, see README.
- added `LogLevel`: TRACE, DEBUG, INFO, WARN, ERROR. Not honored everywhere, mostly for DEBUG and TRACE.
- Nix/Windows compatibility (`exec_(windows/linux).go`), ignore `SwitchUser` on Windows.
- fixed a bug/added a feature with placeholders. They were replaced with values on first call, but following calls would reuse the previous values. This is OK with `%base_dir%`, but not with `%payload_path%` that changes at every request.
- test: new hook scripts and payload sample in `testdata`

2021-10-18 21:35 UTC, monkeydioude commented
great PR overall, would really love to discuss the testing part with you

2021-10-18 21:35 UTC, monkeydioude requested changes

2021-10-18 21:35 UTC, monkeydioude commented on bin/josuke/main.go
> +		//log.Printf("[INFO] add hook %s: %s\n", hook.Name, hook.Path)
little log remaining

2021-10-18 21:35 UTC, monkeydioude commented on bin/josuke/main.go
> +		}
factorizing!
it's amazing!
![factorizing! it's amazing!](http://25.media.tumblr.com/tumblr_lxvceweCo11qff8hqo1_500.gif)

2021-10-18 21:35 UTC, monkeydioude commented on hooks.go
> +		//log.Println(hex.EncodeToString([]byte(s)))
you lost more logs
![](https://www.sasupra.lt/wp-content/uploads/2016/08/log-1.png)

2021-10-18 21:35 UTC, monkeydioude commented on hooks.go
> +		//log.Printf("[INFO] payload signature: %s\n", signature)
![](https://static.wikia.nocookie.net/theforest_gamepedia/images/5/51/LogFarket.png/revision/latest/scale-to-width-down/250?cb=20170924103626)
Tho this one could just be uncommented to allow some syslogs

2021-10-19 10:05 UTC, oparent-sharecare commented on hooks.go
> +		//log.Println(hex.EncodeToString([]byte(s)))
Yes, but activated with the `debug` flag in the configuration. These log statements proved invaluable when checking the payload signature. I can remove them though.

2021-10-19 10:09 UTC, oparent-sharecare commented on bin/josuke/main.go
> +		}
I did not factorize this one because that would have implied searching for a first-letter capitalizing function in Go, to derive the name from the SCM type in lowercase. Plus, GitHub has an additional capital letter in the middle.
OK, I will create a map with SCM definitions, title, name and all.

2021-10-19 10:14 UTC, oparent-sharecare commented on hooks.go
> +		//log.Printf("[INFO] payload signature: %s\n", signature)
All in all, it would be nice to have a log level defined: DEBUG, INFO, WARN, ERROR. I don’t know if something is already available in Go.

2021-10-21 21:34 UTC, pyxide commented
New features:
- SCM Factorizing
- `LogLevel` implemented
- Nix/Windows compatibility (`exec_(windows/linux).go`). One century ago, Java 1.0.2 had already solved this kind of issue, not thoroughly, but yet.

2021-10-21 23:31 UTC, monkeydioude requested changes

2021-10-21 23:31 UTC, monkeydioude commented on josuke.go
> +type Hook struct {
are you a relative of Duck McScrooge ?
Do not hesitate to put new structs and their relatives methods in a separate file

2021-10-21 23:31 UTC, monkeydioude commented on testdata/index.md
> +4. Send the [gogs test payload](gogs-push.json) with `./test gogs`.
"putain" very good!! interesting

2021-10-21 23:31 UTC, monkeydioude commented on users.go
> +
some lost white spaces

2021-10-21 23:31 UTC, monkeydioude commented on bin/josuke/main.go
> +		hh := &josuke.HookHandler{}
We should make a method like NewHookHandler that would return a pointer to a HookHandler struct

2021-10-21 23:31 UTC, monkeydioude commented on hooks.go
> +func ParseScmType(hh *HookHandler, t string) *Scm {
here you could make your var `type2scm` into a custom type and then implement a method called `Parse(...) *Scm` for this custom type

type CustomType map[string]func(hh *HookHandler) *Scm

2021-10-21 23:31 UTC, monkeydioude commented on josuke.go
> +
same as type2scm

2021-10-21 23:38 UTC, monkeydioude commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
do you have precise uses of having"%payload_path%" available inside Josuke's conf ?

2021-10-21 23:41 UTC, monkeydioude commented on hooks.go
> +	if logLevel <= DebugLevel {
I won't ask you to do anymore work about this, I need to contribute as well so I'll make a PR. I have a clear idea on how to do something neat about handling different level of logs

2021-10-22 09:29 UTC, pyxide commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
Delegating the processing of JSON payload with the mighty tool `jq`, in a sub-process, because I’m wondering how the server will handle many requests when each request thread has to wait for the completion of the webhook command.

2021-10-22 09:37 UTC, pyxide commented on hooks.go
> +	if logLevel <= DebugLevel {
I did the simplest thing I could do. I also took a look at [Sirupsen/logrus](https://github.com/Sirupsen/logrus).

2021-10-22 09:53 UTC, pyxide commented on josuke.go
> +type Hook struct {
Haha, I have just followed what the project owner did, adding `Hook` to `Repository`, `Info`, `Branch`… in `josuke.go`. But you know what, it could make sense to move `type Hook` from `josuke.go` to `hooks.go`.

2021-10-22 09:55 UTC, pyxide commented on josuke.go
> +type Hook struct {
On second thought, it’s used to parse the configuration, so it makes sense to have this type here with the others JSON parsed types.

2021-10-22 10:03 UTC, monkeydioude commented on josuke.go
> +type Hook struct {
To be fair, we have to reorganize the whole project, but this seemed a lesser good until then

2021-10-22 10:07 UTC, pyxide commented on josuke.go
> +type Hook struct {
Agreed, let’s do that in an other PR.

2021-10-22 10:11 UTC, pyxide commented on hooks.go
> +func ParseScmType(hh *HookHandler, t string) *Scm {
I will work on it.

2021-10-22 10:13 UTC, pyxide commented on users.go
> +
Done

2021-10-22 10:45 UTC, monkeydioude commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
I don't quite understand "request thread has to wait for the completion of the webhook command.", could you s'il te plait elaborate so my wooden brain would understand ?

2021-10-22 10:47 UTC, monkeydioude commented on hooks.go
> +	if logLevel <= DebugLevel {
yeah logrus is cool, I was actually thinking about this package when writing prior coment, might need some wrapping on our part

2021-10-22 14:51 UTC, pyxide commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
First of all, I don’t know the thread model of the HTTP server. So this may be irrelevant. For the sake of the argument, let’s say that it has a pool of 10 threads to handle incoming requests.
If every webhook launches a command that takes 5 minutes, 10 requests will exhaust the thread pool, and additional requests will fail.

2021-10-22 15:13 UTC, monkeydioude commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
Each request is handled in a coroutine and there is actually no limitation on the number of concurrently running coroutines. Edit: Actually it seems something like "for a machine with 4GB of ram, the amount of concurrent coroutine is a little less than a million"

I think we are going to be just fine

2021-10-22 15:21 UTC, monkeydioude commented on README.md
> +- `command`: optional command, takes precedence over the deployment commands if set. It is run at each valid request. *Only the `%payload_path%` placeholder is available in this hook scope.*
But I understand, that could be useful being able to do something when any payload event comes in.

The way Go handles coroutines is one of its coolest achievements

2021-10-22 22:17 UTC, monkeydioude commented
![](https://github.trello.services/images/mini-trello-icon.png) [[PR] Review de la PR #3](https://trello.com/c/oafTlc4V/1-pr-review-de-la-pr-3)

2021-11-03 15:43 UTC, merged